Added documentation on FHIR
samply/knowledge-base pull request #1
Opened 2020-12-14 14:38 UTC by noemide

2020-12-14 18:01 UTC, alexanderkiel requested changes

2020-12-14 18:01 UTC, alexanderkiel commented on fhir_ig_authoring.md
> +This guideline is intended for developer / data modelers / everyone wanting to extend, adapt or exchange the underlying data model of the Sample Locator. The process of dapting the GUI and queries et
dapting -> adapting, elesewhere -> elsewhere

2020-12-14 18:01 UTC, alexanderkiel commented on fhir_ig_authoring.md
> +It may become necessary to extend the data model, e.g. to add a new criteria tat can be searched for. In this case, you should first answer the following questions:
> e.g. to add a new criteria tat can be searched for.

I would use the term "data elements" instead of criteria here. Criterias are search expressions, while the data itself consists of data elements.

2020-12-14 18:01 UTC, alexanderkiel commented on fhir_ig_authoring.md
> +    *1. Is the addition part of the core GBA IG, the Oncology IG (see below), or should it be a new module?* Is it something all or most participatimg biobanks must or may want to use
The formatting is wrong here, because you indented 4 spaces.

2020-12-14 18:01 UTC, alexanderkiel commented on fhir_ig_authoring.md
> +The way the generated website looks (logos, colors) is specified by a template. This template is specified in one of the configuration files or, if using SUSHI, in the SUSHI configuration file (see S
GBA/BBMRI.de IG - please add a link here

2020-12-15 13:38 UTC, noemide commented on fhir_ig_authoring.md
> +This guideline is intended for developer / data modelers / everyone wanting to extend, adapt or exchange the underlying data model of the Sample Locator. The process of dapting the GUI and queries et
Thanks!

2020-12-15 13:39 UTC, noemide commented on fhir_ig_authoring.md
> +    *1. Is the addition part of the core GBA IG, the Oncology IG (see below), or should it be a new module?* Is it something all or most participatimg biobanks must or may want to use
Removed indention.

2020-12-15 13:39 UTC, noemide commented on fhir_ig_authoring.md
> +It may become necessary to extend the data model, e.g. to add a new criteria tat can be searched for. In this case, you should first answer the following questions:
Good suggestion, I changed the wording.

2020-12-15 13:39 UTC, noemide commented on fhir_ig_authoring.md
> +The way the generated website looks (logos, colors) is specified by a template. This template is specified in one of the configuration files or, if using SUSHI, in the SUSHI configuration file (see S
Added link.

2020-12-15 14:58 UTC, alexanderkiel requested changes

2020-12-15 14:58 UTC, alexanderkiel commented on fhir_ig_authoring.md
> +*1. Is the addition part of the core GBA IG, the Oncology IG (see below), or should it be a new module?* Is it something all or most participating biobanks must or may want to use, or is it only rele
Markdown formatting still doesn't work here. Please remove the `*`: https://daringfireball.net/projects/markdown/syntax#list

2020-12-15 14:58 UTC, alexanderkiel commented on fhir_ig_authoring.md
> +*2. Do other IGs already cover this scope?* A web search for "FHIR + Topic" may find work that other people already have done on this subject. If nothing turns up, ask on the #implementers stream of
I would just use Markdown links instead of plain URL's here.

2020-12-18 17:57 UTC, alexanderkiel approved these changes

2021-01-29 12:52 UTC, merged